add the urdf of dart without spacing.
gdut-dynamic-x/rm_description pull request #6
Opened 2023-01-07 09:53 UTC by d0h0s

2023-01-11 04:09 UTC, qiayuanliao requested changes
你这个 trigger 是 2006 吧，很容易的烧的，limit 搞得这么随便一不小心就烧了

2023-01-11 04:09 UTC, qiayuanliao commented on urdf/dart/dart.urdf.xacro
> +                <joint name="trigger_joint" type="continuous">
永远不会用到 `continuous` joint！永远不会！因为 continuous joint 设置的所所有limit（不只是位置limit，速度和力）都不起作用！！！切记！！！ @ye-luo-xi-tui

2023-01-11 04:09 UTC, qiayuanliao commented on urdf/dart/dart.urdf.xacro
> +                    <limit effort="999" velocity="35.758" lower="0.0" upper="-0.67"/>
999?这么巧的数字吗？

2023-01-11 04:21 UTC, ye-luo-xi-tui commented on urdf/dart/dart.urdf.xacro
> +                <joint name="trigger_joint" type="continuous">
> 永远不会用到 `continuous` joint！永远不会！因为 continuous joint 设置的所所有limit（不只是位置limit，速度和力）都不起作用！！！切记！！！ @ye-luo-xi-tui

这个知道。以后会让他们看过文档再写urdf

2023-01-11 04:23 UTC, qiayuanliao commented on urdf/dart/dart.urdf.xacro
> +                <joint name="trigger_joint" type="continuous">
> > 永远不会用到 `continuous` joint！永远不会！因为 continuous joint 设置的所所有limit（不只是位置limit，速度和力）都不起作用！！！切记！！！ @ye-luo-xi-tui
> 
> 这个知道。以后会让他们看过文档再写urdf

官方urdf文档似乎没写，可能是因为这是和 ros-control 相关的，是ros-control不会对continue joint 做任何限制，如果你们有自己的文档就好了

2023-01-11 04:26 UTC, ye-luo-xi-tui commented on urdf/dart/dart.urdf.xacro
> +                <joint name="trigger_joint" type="continuous">
> > > 永远不会用到 `continuous` joint！永远不会！因为 continuous joint 设置的所所有limit（不只是位置limit，速度和力）都不起作用！！！切记！！！ @ye-luo-xi-tui
> > 
> > 
> > 这个知道。以后会让他们看过文档再写urdf
> 
> 官方urdf文档似乎没写，可能是因为这是和 ros-control 相关的，是ros-control不会对continue joint 做任何限制，如果你们有自己的文档就好了

有自己的文档https://github.com/gdut-dynamic-x/docs/blob/master/source/quick_start/the_method_of_write_urdf.rst
好像没明确说明后续再更新一下

2023-01-11 04:32 UTC, qiayuanliao commented on urdf/dart/dart.urdf.xacro
> +                <joint name="trigger_joint" type="continuous">
> 

吼啊！

2023-01-11 13:33 UTC, d0h0s commented on urdf/dart/dart.urdf.xacro
> +                <joint name="trigger_joint" type="continuous">
收到！

2023-01-11 14:05 UTC, d0h0s commented on urdf/dart/dart.urdf.xacro
> +                <joint name="trigger_joint" type="continuous">
收到！

2023-01-22 16:47 UTC, qiayuanliao commented on urdf/dart/dart.urdf.xacro
> +                    <limit effort="999" velocity="35.758" lower="0.0" upper="-0.67"/>
@ye-luo-xi-tui 咋一直没回复

2023-01-22 22:55 UTC, d0h0s commented on urdf/dart/dart.urdf.xacro
> +                    <limit effort="999" velocity="35.758" lower="0.0" upper="-0.67"/>
> 999?这么巧的数字吗？

我是看目前用的飞镖的rm_description用的是这个数字就继续用了，暂时还没学会算合适的limit

2023-01-24 09:17 UTC, qiayuanliao commented on urdf/dart/dart.urdf.xacro
> +                    <limit effort="999" velocity="35.758" lower="0.0" upper="-0.67"/>
好的，如果要给无限大，应该参考步兵轮子的位置限制 (1e16 好像是，我忘记了)。但明显这里一定要给扭矩限制，因为使用了2006，一不小心就烧掉了。 @ye-luo-xi-tui 尽快教会他们怎么算。

2023-01-24 09:19 UTC, qiayuanliao requested changes

2023-01-24 09:19 UTC, qiayuanliao commented on urdf/dart/dart.urdf.xacro
> +    <xacro:arg name="load_shooter" default="true"/>
这三行没用呀hhh

2023-01-24 09:19 UTC, qiayuanliao commented on urdf/dart/dart.urdf.xacro
> +    <xacro:arg name="load_shooter" default="true"/>
飞镖就没必要能分模块加载了，这是之前步兵测试分模块用滴

2023-01-25 10:21 UTC, d0h0s commented on urdf/dart/dart.urdf.xacro
> +    <xacro:arg name="load_shooter" default="true"/>
> 飞镖就没必要能分模块加载了，这是之前步兵测试分模块用滴

收到！

2023-01-26 07:21 UTC, ye-luo-xi-tui commented on urdf/dart/dart.urdf.xacro
> +            </collision>
这些和下面那些link的这些信息都可以删掉，这些是仿真才会用的，飞镖根本没有跑仿真的必要

2023-01-26 07:23 UTC, ye-luo-xi-tui commented on urdf/dart/dart.urdf.xacro
> +            <link name="right_pitch"/>
left_pitch 和right_pitch是为啥来着

2023-01-26 07:27 UTC, ye-luo-xi-tui commented on urdf/dart/dart.urdf.xacro
> +                    <limit effort="999" velocity="35.758" lower="0.0" upper="-0.67"/>
> > 999?这么巧的数字吗？
> 
> 我是看目前用的飞镖的rm_description用的是这个数字就继续用了，暂时还没学会算合适的limit

通常执行器输出最大扭矩时对应的关节扭矩就是limit。根据具体用的电机最大能输出多大扭矩决定

2023-01-29 11:58 UTC, d0h0s commented on urdf/dart/dart.urdf.xacro
> +            <link name="right_pitch"/>
因为控制飞镖的Pitch用了左右两个电机转动转动丝杆

2023-01-29 11:59 UTC, d0h0s commented on urdf/dart/dart.urdf.xacro
> +            </collision>
> 这些和下面那些link的这些信息都可以删掉，这些是仿真才会用的，飞镖根本没有跑仿真的必要

好的

2023-01-29 12:03 UTC, d0h0s commented on urdf/dart/dart.urdf.xacro
> +            </collision>
> 这些和下面那些link的这些信息都可以删掉，这些是仿真才会用的，飞镖根本没有跑仿真的必要

有些是软限位相关参数我就不删了

2023-01-29 12:34 UTC, ye-luo-xi-tui commented
commit信息必须要用英文

2023-01-30 06:03 UTC, ye-luo-xi-tui commented
没有缩进的必要啊，为什么要缩进

2023-01-30 06:46 UTC, d0h0s commented
> 没有缩进的必要啊，为什么要缩进
之前有是否加载模块判断，删掉之后没删缩进，现在改

2023-01-31 08:46 UTC, d0h0s commented
> 没有缩进的必要啊，为什么要缩进

已更改

2023-01-31 14:10 UTC, qiayuanliao commented
> 

出现这种情况大概率是你 CLion 没有配置好，要检查

2023-02-01 09:01 UTC, ye-luo-xi-tui commented
还有几个关节的限制力矩没改

2023-02-01 16:14 UTC, d0h0s commented
> > 
> 
> 出现这种情况大概率是你 CLion 没有配置好，要检查

好的 我重新检查一下

2023-02-01 16:16 UTC, d0h0s commented
> 还有几个关节的限制力矩没改

其他的都是无传动比的关节 我就直接参照别的机器人上的同型号电机来填了

2023-03-02 13:49 UTC, qiayuanliao approved these changes

2023-03-10 09:06 UTC, closed without merging